### ISSUE TITLE
 Open source the Looking Glass

### ISSUE THREAD

**Issue by mattdavis0351** [githubtraining/looking-glass-action#6]
@githubtraining/programs Should we open source Looking Glass.

With the potential to have help from the folks at Microsoft as well as how many people may be writing hands-on labs in the future it may be worthwhile to open this thing up for community contributions.

What are everyones thoughts on this?

**Comment by lmkeston** [comment]
I like this idea @mattdavis0351!

**Comment by brianamarie** [comment]
I think this is a great idea, @mattdavis0351!

**Comment by hectorsector** [comment]
@mattdavis0351 Looking Glass is currently public, and has an MIT license. The exercises are public, as well. Any other action items on here?

**Comment by mattdavis0351** [comment]
@hectorsector I don't think so.  As long as we aren't breaking some GitHub Open Source rules that we aren't aware of then I think this issue is ready to be closed if we consider this enough to be done.

**Comment by hectorsector** [comment]
We'e done our due diligence. Thanks for helping out with this @mattdavis0351 ❤️
